   Cell/Matrix Properties 
voxelSizeNm,5;
memorySizeMb,24000;
modelTimeStepSec,0.005;
cellSizeXnm,2600;
cellSizeYnm,1000;
cellSizeZnm,1000;
sideGapNm,200;
topGapNm,20;
botGapNm,20;
roundedCellBody,ON;
cellFilletNm,500;
nucleusRadNm,400;
flattening,1.2;
nucleus,OFF;
rafts,OFF;
raftNumber,100;
raftRadNm,100;
raftMobilityRatio,0.1;
interactionDistanceUm,0.005;
filopodia,OFF;
lamella,OFF;
tubes,ON;
tubeNetwork,OFF;
tubeRadNm,450;
tubeLengthNm,1600;
interTubeDistNm,1000;
tubeZnm,520;
tubeGapNm,30;
bendingCoef,0;
tube3D,OFF;
vesicleRadNm,100;
vesicleNumber,1;
movingVesicles,OFF;
vesRecycling,OFF;
outsideVesicles,OFF;
vesicleMob,0.02;
fuseVesicles,OFF;
instantRelease,ON;
poreRadNm,100;

  Illumination Settings;
FWHMnm,250;
greenPhotonsPerSec,6000;
greenBleachRate,0.05;
redPhotonsPerSec,10000;
redBleachRate,0.02;
greenBlinking,OFF;
greenBlinkONrate,1;
greenBlinkOFFrate,5;
FRET,OFF;
alternatingIllumination,OFF;
laserFWHMum,100;
diaphragmRadUm,50;
bleachSizeNm,5000;

  Camera Settings;
objectiveLensZcoef,0.6;
cameraNmPix,5;
focusNm,400;
twoCameraMode,OFF;
EMCCDmode,ON;
cameraGain,5;
timeStepsPerImage,10;
darkFramesNumber,0;
cameraNoiseCountsPix,1.5;
FramesToSave,0;

  CytoA Object Settings;
cytoAnumber,1000;
cytoAdistribution,VESICLES;
greenFluorsPerCytoA,0;
greenFractionCytoA%,100;
redFluorsPerCytoA,1;
redFractionCytoA%,100;
cytoAdiffusionRate,0.5;
cytoAstepSizeNm,8;
cytoAstepRate,100;
cytoApolimer,OFF;
cytoApolimerRate,500000;
cytoAdepolimerRate,0.1;

  CytoB Object Settings;
cytoBnumber,0;
cytoBdistribution,CYTOPLASM;
greenFluorsPerCytoB,3;
greenFractionCytoB%,50;
redFluorsPerCytoB,4;
redFractionCytoB%,80;
cytoBdiffusionRate,2;
cytoAbindingCytoB,OFF;
cytoAcytoBbindRate,1000000;
cytoAcytoBdissRate,0.1;

  MembA Object Settings;
membAnumber,2000;
membAdistribution,VESICLE_MEMBRANE;
greenFluorsPerMembA,1;
greenFractionMembA%,100;
redFluorsPerMembA,0;
redFractionMembA%,100;
membAdiffusionRate,0.1;
cytoAbindingMembA,OFF;
cytoAmembAbindRate,1000000;
cytoAmembAdissRate,0.2;
membAorganellePump,OFF;
membApolimer,OFF;
membApolimerRate,100000;
membAdepolimerRate,1;
membAmaxUnitPolimer,8;

  MembB Object Settings;
membBnumber,0;
membBdistribution,NUCLEUS_MEMBRANE;
greenFluorsPerMembB,0;
greenFractionMembB%,100;
redFluorsPerMembB,1;
redFractionMembB%,100;
membBdiffusionRate,0.1;
cytoAbindingMembB,OFF;
cytoAmembBbindRate,1000000;
cytoAmembBdissRate,0.01;
membBcytoplasmPump,OFF;
membAbindingMembB,OFF;
membAmembBbindRate,10000;
membAmembBdissRate,0.1;

  MembC Object Settings;
membCnumber,0;
membCdistribution,NUCLEUS_MEMBRANE;
greenFluorsPerMembC,0;
greenFractionMembC%,100;
redFluorsPerMembC,4;
redFractionMembC%,100;
membCdiffusionRate,0.03;
membBbindingMembC,ON;
membBmembCbindRate,100000;
membBmembCdissRate,1;

  StatA Object Settings;
statAnumber,0;
statAdistribution,STRAIT_FIBERS_XY;
greenFluorsPerStatA,2;
greenFractionStatA%,100;
redFluorsPerStatA,0;
redFractionStatA%,100;
statAmonomerDistanceNm,8;
statAmonoPerFilo,200;
statAbundleExtensionNm,50;
statAbindingCytoA,OFF;
cytoAstatAbindRate,500000;
cytoAstatAdissRate,0.1;
cytoAmoveAlongStatA,OFF;
